export const ActionQuizType = {
  ACTION_QUIZ_START: 'ACTION_QUIZ_START',
  ACTION_QUIZ_SUCCESS: "ACTION_QUIZ_SUCCESS",
  ACTION_QUIZ_ERROR: "ACTION_QUIZ_ERROR",
  ACTION_QUIZ_SUCCESS_ID: "ACTION_QUIZ_SUCCESS_ID",
  ANSWER_QUIZ: "ANSWER_QUIZ",
  ANSWER_NEXT_STEP: "ANSWER_NEXT_STEP",
  RESET_QUIZ: "RESET_QUIZ"
}

