export const ActionQuizType = {
  ACTION_QUIZ_START: 'ACTION_QUIZ_START',
  ACTION_QUIZ_SUCCESS: "ACTION_QUIZ_SUCCESS",
  ACTION_QUIZ_ERROR: "ACTION_QUIZ_ERROR",
  ACTION_QUIZ_SUCCESS_ID: "ACTION_QUIZ_SUCCESS_ID"
}

